import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout-components/root-navbar";
import { UserPreferencesProvider } from "@/components/providers/UserPreferencesContext";
import { Analytics } from "@vercel/analytics/react";
import { TopBar } from "@/components/layout-components/contact-info-baner-top";
import { FooterComponent } from "@/components/layout-components/footer-component";
import { Toaster } from "@/components/ui/toaster"
import {AccessibilityPanel} from "@/components/providers/accessibility-panel";
import BanerIviteHomePage from "@/components/home-page-components/baner-invite-home-page";



const dmsans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Instytut Studiów Podyplomowych BIS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmsans.className} overflow-x-hidden`}>
        <UserPreferencesProvider>
          {/* <Access /> */}
          <TopBar />
          <Navbar />
          <BanerIviteHomePage/>
          <main>{children}</main>
          <AccessibilityPanel />
          <Toaster />
          <Analytics />
          <FooterComponent />
        </UserPreferencesProvider>
      </body>
    </html>
  );
}
